// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: ioam_api.proto

package ioam_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IOAMServiceClient is the client API for IOAMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IOAMServiceClient interface {
	// Report an IOAM Trace
	Report(ctx context.Context, in *IOAMTrace, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type iOAMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIOAMServiceClient(cc grpc.ClientConnInterface) IOAMServiceClient {
	return &iOAMServiceClient{cc}
}

func (c *iOAMServiceClient) Report(ctx context.Context, in *IOAMTrace, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ioam_api.IOAMService/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IOAMServiceServer is the server API for IOAMService service.
// All implementations must embed UnimplementedIOAMServiceServer
// for forward compatibility
type IOAMServiceServer interface {
	// Report an IOAM Trace
	Report(context.Context, *IOAMTrace) (*emptypb.Empty, error)
	mustEmbedUnimplementedIOAMServiceServer()
}

// UnimplementedIOAMServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIOAMServiceServer struct {
}

func (UnimplementedIOAMServiceServer) Report(context.Context, *IOAMTrace) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedIOAMServiceServer) mustEmbedUnimplementedIOAMServiceServer() {}

// UnsafeIOAMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IOAMServiceServer will
// result in compilation errors.
type UnsafeIOAMServiceServer interface {
	mustEmbedUnimplementedIOAMServiceServer()
}

func RegisterIOAMServiceServer(s grpc.ServiceRegistrar, srv IOAMServiceServer) {
	s.RegisterService(&IOAMService_ServiceDesc, srv)
}

func _IOAMService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IOAMTrace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOAMServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ioam_api.IOAMService/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOAMServiceServer).Report(ctx, req.(*IOAMTrace))
	}
	return interceptor(ctx, in, info, handler)
}

// IOAMService_ServiceDesc is the grpc.ServiceDesc for IOAMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IOAMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ioam_api.IOAMService",
	HandlerType: (*IOAMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _IOAMService_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ioam_api.proto",
}
