FROM ntop/pfring

RUN apt-get update && \
    apt-get -y install golang

RUN apt-get update && \
    apt-get -y install protoc-gen-go protoc-gen-go-grpc

RUN apt-get update && \
    apt-get -y install iproute2

WORKDIR /apps

# Generate grpc cpp code, and compile ioam agent
COPY ioam_api.proto .
RUN protoc --go_out=. --go-grpc_out=. ioam_api.proto
COPY *.go .
RUN go mod init ioam-agent-go
RUN go mod tidy
RUN go build -tags pfring -o ioam-agent

ENTRYPOINT ["./ioam-agent"]
CMD ["-h"]
