// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ioam_api

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// IOAMServiceClient is the client API for IOAMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IOAMServiceClient interface {
	// Report an IOAM Trace
	Report(ctx context.Context, opts ...grpc.CallOption) (IOAMService_ReportClient, error)
}

type iOAMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIOAMServiceClient(cc grpc.ClientConnInterface) IOAMServiceClient {
	return &iOAMServiceClient{cc}
}

func (c *iOAMServiceClient) Report(ctx context.Context, opts ...grpc.CallOption) (IOAMService_ReportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IOAMService_serviceDesc.Streams[0], "/ioam_api.IOAMService/Report", opts...)
	if err != nil {
		return nil, err
	}
	x := &iOAMServiceReportClient{stream}
	return x, nil
}

type IOAMService_ReportClient interface {
	Send(*IOAMTrace) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type iOAMServiceReportClient struct {
	grpc.ClientStream
}

func (x *iOAMServiceReportClient) Send(m *IOAMTrace) error {
	return x.ClientStream.SendMsg(m)
}

func (x *iOAMServiceReportClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IOAMServiceServer is the server API for IOAMService service.
// All implementations must embed UnimplementedIOAMServiceServer
// for forward compatibility
type IOAMServiceServer interface {
	// Report an IOAM Trace
	Report(IOAMService_ReportServer) error
	mustEmbedUnimplementedIOAMServiceServer()
}

// UnimplementedIOAMServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIOAMServiceServer struct {
}

func (UnimplementedIOAMServiceServer) Report(IOAMService_ReportServer) error {
	return status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedIOAMServiceServer) mustEmbedUnimplementedIOAMServiceServer() {}

// UnsafeIOAMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IOAMServiceServer will
// result in compilation errors.
type UnsafeIOAMServiceServer interface {
	mustEmbedUnimplementedIOAMServiceServer()
}

func RegisterIOAMServiceServer(s *grpc.Server, srv IOAMServiceServer) {
	s.RegisterService(&_IOAMService_serviceDesc, srv)
}

func _IOAMService_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IOAMServiceServer).Report(&iOAMServiceReportServer{stream})
}

type IOAMService_ReportServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*IOAMTrace, error)
	grpc.ServerStream
}

type iOAMServiceReportServer struct {
	grpc.ServerStream
}

func (x *iOAMServiceReportServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *iOAMServiceReportServer) Recv() (*IOAMTrace, error) {
	m := new(IOAMTrace)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _IOAMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ioam_api.IOAMService",
	HandlerType: (*IOAMServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _IOAMService_Report_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ioam_api.proto",
}
